### ISSUE TITLE
Use different yaml formatter

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_lint#152]
@f0rmiga reports that prettier does some non-conventional things to yaml files. Maybe we should run those through https://github.com/google/yamlfmt instead

**Comment by IamXander** [comment]
Can I see a few examples of what the "non-conventional-ness" of prettier is? I think adding a new tool in this project works fine but the problem is that the more formatting tools we have the worse the experience is for users. 99% of the time these integrations should be baked into the IDE of the user (meaning they never run the bazel command). Prettier has first class IDE support and it is a shame that if we wanted to use this tool we would have to figure out how to add yet another formatter.
