### ISSUE TITLE
[Bug]: generated code will be format. (.go)

### ISSUE THREAD

**Issue by hunshcn** [aspect-build/rules_lint#205]
### What happened?

gofumpt will not format generated code https://github.com/mvdan/gofumpt/pull/150.
but due to https://github.com/mvdan/gofumpt/pull/195 , the behavior of `gofumpt dir` and `gofumpt file` is different.

rules_lint find all .go files, and execute with `gofumpt file`. It will cause generated code formatted.

There seems to be no solution at present (also we can't ignore generated file)

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 7.1.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 0.18.0

Language(s) and/or frameworks involved: go

**Comment by alexeagle** [comment]
I think it's a special case of https://github.com/aspect-build/rules_lint/issues/151 ?

- cannot configure gofumpt with a config file that has excludes
- gofumpt doesn't honor the `.gitattributes` file that says it's generated
- generated file cannot opt-out of formatting with a comment at the top

I imagine this could also be fixed by changes to gofumpt. Any fix in rules_lint should be general, so I think it's exactly #151

**Comment by mrmeku** [comment]
@alexeagle This pattern was one of my motivations for filing #151

**Comment by alexeagle** [comment]
Fix is coming in https://github.com/aspect-build/rules_lint/pull/210

**Comment by alexeagle** [comment]
Fixed at head
