### ISSUE TITLE
[FR]: bring ruff and vale to multitool

### ISSUE THREAD

**Issue by hunshcn** [aspect-build/rules_lint#279]
### What is the current behavior?

fetch_ruff("0.0.0")

### Describe the feature

bring them to multitool will make bzlmod users more convenient to use.

According to the method of https://github.com/theoremlp/rules_multitool/issues/32#issuecomment-2085524640

But for workspace users, I can't think of an elegant way to interact.

If there is any hope to modify this aspect, it may need to be completed before the official release of v1.0.0? Because there may be some changes in the way of interaction.

**Comment by hunshcn** [comment]
Or maintain the status quo, bzlmod users can introduce ruff by themselves through multitool.

I'm doing this now, and I feel good. And I can easily update ruff through multitool.

**Comment by alexeagle** [comment]
Ruff is done.

For Vale, it's more complex, since they have a plugin ecosystem they refer to as "Styles". Multitool could download the vale tool, but users still need to do something to fetch these styles, and we need to pin them somewhere (see `VALE_STYLE_DATA` in `lint/vale_library.bzl`)

Although it's possible that multitool could fetch the styles as well, IMHO it's not worth the effort for me to switch this over, I think vale usage will be an order of magnitude less than Ruff.
