### ISSUE TITLE
[Bug]: Lints reported on generated files

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_lint#90]
### What happened?

Haven't verified, but we think we currently run linters on all `srcs` of a `*_library` including those in `bazel-out` which means we're reporting lint violations on generated code. This is not desirable, we should probably filter them out.

Follow-up from #62 

### Version

HEAD

**Comment by gregmagolan** [comment]
Related to this, the line in ruff.bzl can be `.path` instead of `.short_path`: https://github.com/aspect-build/rules_lint/blob/31abe826d0a5c2d1c2f68e145103a8e18480b505/lint/ruff.bzl#L93

The `.short_path` is only needed to `eslint.bzl` where we're translating copied source files in the output tree to their original source tree location.
